const data = {
  users: [],
  products: [
    {
      _id: "1",
      izina: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "T-shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "NIKE",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      _id: "2",
      izina: "Nike slim pants",
      slug: "6",
      category: "pants",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 0,
      brand: "NIKE",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      _id: "3",
      izina: "adidas slim shirt",
      slug: "adidas-slim-shirt",
      category: "T-shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 1,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      _id: "4",
      izina: "adidas slim pant",
      slug: "3",
      category: "T-shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 2.5,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
  ],
};

export default data;
